
import "./globals.css";
import { Montserrat } from "next/font/google";
const montseerat = Montserrat({ subsets: ["vietnamese"] });

export const metadata = {
  title: "Health Care",
  description: "Generated by METCH",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="rtl">
      
      <body
        className={`${montseerat.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
